#:schema ./.schema/users.schema.json
#
# Basic users configuration.
#
[[users]]
name = "pgdog"
database = "pgdog"
password = "pgdog"

[[users]]
name = "pgdog"
database = "pgdog_sharded"
password = "pgdog"
