[package]
name = "pgdog-jsonschema"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0"
pgdog-config.workspace = true
schemars.workspace = true
serde_json.workspace = true
workspace_root = "0.2.0"
