[general]
pub_sub_channel_size = 4098

[rewrite]
enabled = false
shard_key = "ignore"
split_inserts = "error"

[[databases]]
name = "pgdog"
host = "127.0.0.1"
pooler_mode = "statement"


[admin]
password = "pgdog"
