[general]
resharding_copy_format = "binary"
load_schema = "on"
cutover_timeout_action = "cutover"

[[databases]]
name = "source"
host = "127.0.0.1"
port = 15432
database_name = "pgdog"

[[databases]]
name = "destination"
host = "127.0.0.1"
port = 15433
database_name = "pgdog1"
shard = 0

[[databases]]
name = "destination"
host = "127.0.0.1"
port = 15434
database_name = "pgdog2"
shard = 1

[[sharded_tables]]
database = "destination"
column = "tenant_id"
data_type = "bigint"

[admin]
password = "pgdog"
