[general]
expanded_explain = true

[[databases]]
name = "pgdog"
host = "127.0.0.1"
shard = 0
database_name = "shard_0"

[[databases]]
name = "pgdog"
host = "127.0.0.1"
shard = 1
database_name = "shard_1"

[admin]
password = "pgdog"

[[omnisharded_tables]]
database = "pgdog"
tables = [
    "pg_class",
    "pg_namespace",
    "pg_am"
]
sticky_routing = true
