[general]
port                      =   6432
workers                   =   8
default_pool_size         =   2000
min_pool_size             =   0
pooler_mode               =   "transaction"
healthcheck_port          =   8080
healthcheck_interval      =   30_000
idle_healthcheck_interval =   30_000
idle_healthcheck_delay    =   5_000
healthcheck_timeout       =   5_000
ban_timeout               =   15000
rollback_timeout          =   30000
load_balancing_strategy   =   "round_robin"
read_write_strategy       =   "conservative"
read_write_split          =   "exclude_primary"
tls_verify                =   "prefer"
shutdown_timeout          =   60_000
prepared_statements       =   "extended"
passthrough_auth          =   "disabled"
connect_timeout           =   15000
connect_attempts          =   3
connect_attempt_delay     =   0
checkout_timeout          =   15000
dry_run                   =   false
idle_timeout              =   600000
mirror_queue              =   128
mirror_exposure           =   1.0
auth_type                 =   "scram"
cross_shard_disabled      =   false
dns_ttl                   =   1000
openmetrics_port = 9090
openmetrics_namespace = "pgdog_"
server_lifetime = 86400000
log_connections = true
log_disconnections = true
expanded_explain = false
lsn_check_delay           =   0
[[databases]]
name = "postgres"
host = "aurora-2-instance-1.c5icciqq4b0q.us-west-2.rds.amazonaws.com"
port = 5432
shard = 0
role = "replica"
[[databases]]
name = "postgres"
host = "aurora-2-instance-2.c5icciqq4b0q.us-west-2.rds.amazonaws.com"
port = 5432
shard = 0
role = "auto"
[[databases]]
name = "postgres"
host = "aurora-2-instance-3.c5icciqq4b0q.us-west-2.rds.amazonaws.com"
port = 5432
shard = 0
role = "auto"
[tcp]
time = 120000
interval = 30000
retries = 10

[admin]
password = "pgdog"
