[general]
lsn_check_delay = 1000000
lsn_check_interval = 5_000
idle_timeout = 1_000

[[databases]]
name = "postgres"
role = "primary"
host = "127.0.0.1"
port = 45000

[[databases]]
name = "postgres"
role = "replica"
host = "127.0.0.1"
port = 45001

[[databases]]
name = "postgres"
role = "replica"
host = "127.0.0.1"
port = 45002

[admin]
password = "pgdog"
